#cloud-config

mounts:
  - ["/dev/nvme1n1", "/mnt", "ext4", "defaults,nofail", "0", "2"]

runcmd:
  - /bootstrap.sh

write_files:
  - content: |
      #!/bin/bash -eux

      sudo apt update -y
      sudo apt install -y nodejs
      sudo mount /mnt
      sudo hostname localhost.localdomain

      sudo -u admin node /mnt/${VERSION}/App/resources/app/main.js --dataPath=/mnt/${VERSION}/${WORLD} --port=30000 --headless --noUpdate

      touch /bootstrap
    owner: root:root
    path: /bootstrap.sh
    perms: "0755"

